// TransmissionRuleEditorDefs.h
// Generated by Interface Elements (Window v2.3) on Apr 3 1999
// Do not modify this file!



/*

Views in Transmission Rule Editor:
	<unnamed> (BTabView)
	"General"  (BView)
	"Enable Transmission"  (BCheckBox)
	<unnamed> (BBox)
	"Ordering - None"  (BRadioButton)
	"Ordering - sender"  (BRadioButton)
	"Ordering - receiver"  (BRadioButton)
	"Ordering - Some"  (BRadioButton)
	<unnamed> (BBox)
	"cycle suits"  (BCheckBox)
	"cycle values"  (BCheckBox)
	"Pile Ordering - Suit Steps"  (BMenuField)
	"_mc_mb_"  (_BMCMenuBar_)
	"Pile Ordering - Value Steps"  (BMenuField)
	"_mc_mb_"  (_BMCMenuBar_)
	"update"  (BButton)
	<unnamed> (BBox)
	"Ordering - Block"  (BRadioButton)
	"Ordering - UF Clean"  (BRadioButton)
	"Ordering - UF Messy"  (BCheckBox)
	"allowed # - min"  (BTextControl)
	"_input_"  (_BTextInput_)
	"allowed # - max"  (BTextControl)
	"_input_"  (_BTextInput_)
	"update sym"  (BButton)
	<unnamed> (BView)
	"Selected"  (BBox)
	<unnamed> (BStringView)
	<unnamed> (BStringView)
	<unnamed> (BScrollView)
	"check view"  (BView)

*/


// Message constants:
enum {
	IE_TRANSMISSIONRULEEDITOR_ENABLETRANSMISSION = 0x1L,
	IE_TRANSMISSIONRULEEDITOR_ORDERINGNONE = 0x1DL,
	IE_TRANSMISSIONRULEEDITOR_ORDERINGSENDER = 0x20L,
	IE_TRANSMISSIONRULEEDITOR_ORDERINGRECEIVER = 0x27L,
	IE_TRANSMISSIONRULEEDITOR_ORDERINGSOME = 0x25L,
	IE_TRANSMISSIONRULEEDITOR_CYCLESUITS = 0x62L,
	IE_TRANSMISSIONRULEEDITOR_CYCLEVALUES = 0x5EL,
	IE_TRANSMISSIONRULEEDITOR_PILEORDERINGSUITSTEPS_TOGGLE_ALL = 0xC5L,
	IE_TRANSMISSIONRULEEDITOR_PILEORDERINGVALUESTEPS_TOGGLE_ALL = 0xC3L,
	IE_TRANSMISSIONRULEEDITOR_UPDATE = 0x6CL,
	IE_TRANSMISSIONRULEEDITOR_ORDERINGBLOCK = 0xABL,
	IE_TRANSMISSIONRULEEDITOR_ORDERINGUFCLEAN = 0xADL,
	IE_TRANSMISSIONRULEEDITOR_ORDERINGUFMESSY = 0xA9L,
	IE_TRANSMISSIONRULEEDITOR_ALLOWEDMIN = 0x77L,
	IE_TRANSMISSIONRULEEDITOR_ALLOWEDMAX = 0x7DL,
	IE_TRANSMISSIONRULEEDITOR_UPDATESYM = 0x84L
};

